name: Syntax and Deprecation Check

on:
  push:
    paths:
      - index.php
  pull_request:
    paths:
      - index.php

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install

      - name: Install PHPStan and Deprecation Rules
        run: composer require --dev phpstan/phpstan phpstan/phpstan-deprecation-rules

      - name: Syntax check for index.php
        run: php -l index.php

      - name: Run PHPStan for deprecation checks
        run: vendor/bin/phpstan analyse index.php
