name: 'Terraform Check'

on:
  push:

permissions:
  security-events: write
  contents: read
  actions: read

jobs:
  terraform-unit-tests:
    name: 'Terraform Unit Tests'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init -backend=false

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check -recursive
      continue-on-error: true
